### ISSUE TITLE
Creeper explosions do not count towards the progress bar

### ISSUE THREAD

**Issue by CalaMariGold** [Rebirth-of-the-Night/onslaught#2]
Applies to all types of creepers. Might apply to other mobs that are blown up by TNT too.

**Comment by CalaMariGold** [comment]
@codetaylor Do you have an idea for how this would be fixed?

**Comment by codetaylor** [comment]
Not off the top of my head, no. I'd have to spin the project back up and
dig into it. It's been a while since I worked on it.

**Comment by SekretOne** [comment]
I had a hunch- the explosion isn't exactly a death. Killed and removed is not necessarily the same thing.

https://forums.minecraftforge.net/topic/64647-minecraft-forge-1112-creeper-explosion-not-firing-livingdeath-event/

Believe that can be fixed by adding a subscriber to the explosion event.

There may be other ways for a mob to 'end' but not technically die. Falling death, or dying to environment should be okay. However, Mods that say 'capture a mob' and put it in a ball ... may effective remove the entity without its death or explosion.
